# Generated by tools/vendor_guard_rules.py from src/provenrail/transcript.py. Do not edit:
# edit the source module and regenerate, or the two engines will disagree.
"""Spend read off the agent's own transcript, so a cap can bind at the tool boundary.

A `PreToolUse` hook is handed a `transcript_path` and nothing else about money. The transcript
it points at holds one line per assistant message with `message.model` and `message.usage`, and
`pricing.cost_for` already prices every key in it. Nothing joined the two, so the product's own
budget feature capped nothing in the install it recommends: the hook saw no model calls, the
ledger stayed empty, and `pr guard status` reported a budget as armed while it bound no dollar
at all. This module is that join.

Three properties, each of them the difference between a cap and a decoration:

**Incremental, and it never charges the same message twice.** A streamed message is written to
the transcript several times as it grows, every one of those lines sharing `message.id`, and the
last one carries the final usage. Pricing every line would multiply an ordinary turn's cost by
its number of chunks and deny a $25 day cap by lunchtime; pricing only the first would undercount
every streamed reply. So each read starts at the byte offset the previous read ended at, carries
forward what it already charged the ids at the tail, and charges only the increase.

**An unreadable or truncated transcript is UNKNOWN, never zero.** This is the same rule
`spend.prior_spend` holds for the ledger and for the same reason: a $0.00 reported on authority
lifts the cap at precisely the moment the machine is in trouble. `state.known` is False after any
read that could not be completed, and the guard says so on stderr rather than silently allowing.

**Whole lines only.** The hooks documentation says the transcript "is written asynchronously and
may lag", so the tail of the file is routinely half a line. A partial line is left unconsumed and
the offset is not advanced past it, which is also what makes enforcement land within a turn rather
than at the exact dollar. The copy says "within a turn" and must keep saying that.

The budget verdict itself lives here too, and that is deliberate. Two engines answer a hook (the
installed CLI and the vendored standalone in `plugins/provenrail-guard/`), this file is vendored
into the second one by `tools/vendor_guard_rules.py`, and a dollar figure or a deny sentence
written twice is a dollar figure that will eventually differ between them. It is written once,
here, and both engines call it.

Stdlib only, apart from `pricing`, because it is vendored.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

try:                                  # installed as part of the package
    from .pricing import cost_for, reliable
except ImportError:                   # vendored: the hook imports it as a top-level module
    from pricing import cost_for, reliable  # type: ignore[no-redef]

#: How many recently seen message ids the state remembers so their cost can be corrected
#: upwards as a streamed message grows. The partials of one message are written consecutively,
#: so a handful would do; this is sized to survive interleaving we have not seen yet while
#: keeping the state file small enough to rewrite on every tool call.
RECENT_IDS = 64

#: Said wherever a dollar figure produced here is shown to a person. The number is derived from
#: reported token counts and public list prices, and on a Pro or Max subscription no per-token
#: charge exists at all, so presenting it as an amount owed would be a claim we cannot defend.
ESTIMATE_CAVEAT = "estimated at API list price, and notional on Pro and Max flat-rate plans"

#: The rule id a budget fires when spend cannot be counted at all. Shared with `policy.decide`
#: so a dashboard sees one id for one condition.
UNPRICED_RULE = "budget.unpriced"

# The budget scopes, and what each of them counts. They live in this module rather than in
# `policy.py` for one reason: the zero-install engine has to validate a scope and add up the
# same figure, it cannot import `policy`, and a second copy of a three-item list is a second
# copy that will eventually disagree about what `day` means. `policy` re-exports them.
SESSION = "session"
DAY = "day"
TOTAL = "total"
BUDGET_SCOPES = (SESSION, DAY, TOTAL)

#: Every field a budget may carry. Both engines reject anything else rather than ignoring it: a
#: misspelled field would silently disable the cap while the config still read like one.
BUDGET_FIELDS = ("id", "scope", "limit_usd", "warn_at")


def spent_by_scope(session_usd: float, prior_day_usd: float,
                   prior_total_usd: float) -> dict[str, float]:
    """Estimated spend against each scope, this session included.

    The scope is the whole point of a budget. The failure teams actually have is not one session
    that costs too much, it is an agent running all night across hundreds of short sessions and
    discovered when the invoice arrives, which a `session` cap cannot see and a `day` cap can.
    """
    return {SESSION: session_usd,
            DAY: prior_day_usd + session_usd,
            TOTAL: prior_total_usd + session_usd}


@dataclass
class TranscriptState:
    """Where the last read stopped, and what it had already charged.

    Persisted in `.provenrail-guard-counts.json`, because every hook invocation is its own
    process: a state kept in memory would restart at offset zero on every tool call and charge
    the whole transcript again each time. It is persisted as two halves under two keys, see
    `state_key` and `find_state`, because the read cursor belongs to the transcript while the
    session total belongs to the session.
    """

    offset: int = 0
    #: message id -> the cost already charged for it, for the most recent ids only.
    charged: dict[str, float] = field(default_factory=dict)
    #: Everything this transcript has cost, for a `session`-scope budget. The ledger cannot
    #: answer that question: it buckets by day and by agent, not by session.
    session_usd: float = 0.0
    unpriced_calls: int = 0
    #: False when the last read could not be completed, so every figure derived from it is a
    #: floor rather than a total.
    known: bool = True

    def cursor_dict(self) -> dict[str, Any]:
        """The half that belongs to the transcript: how far it was read, and what it charged."""
        return {"offset": self.offset, "charged": dict(self.charged),
                "unpriced_calls": self.unpriced_calls}

    def session_dict(self) -> dict[str, Any]:
        """The half that belongs to the host session, which is what a `session` cap counts."""
        return {"session_usd": round(self.session_usd, 6)}

    def to_dict(self) -> dict[str, Any]:
        """Both halves, for a reader that holds them together rather than persisting them."""
        return {**self.cursor_dict(), **self.session_dict()}

    @classmethod
    def from_dict(cls, data: Any) -> TranscriptState:
        """Rebuild from the state file, tolerating anything that is not what we wrote.

        A mangled state file must not read as "offset 0, nothing charged", which would recharge
        the entire transcript; it reads as a fresh state whose `known` is False, so the caller
        reports the figure as incomplete instead of acting on it.
        """
        if not isinstance(data, dict):
            return cls(known=False)
        try:
            offset = int(data.get("offset", 0))
            session_usd = float(data.get("session_usd", 0.0) or 0.0)
            unpriced = int(data.get("unpriced_calls", 0) or 0)
        except (TypeError, ValueError):
            return cls(known=False)
        charged_raw = data.get("charged")
        charged: dict[str, float] = {}
        if isinstance(charged_raw, dict):
            for key, value in charged_raw.items():
                try:
                    charged[str(key)] = float(value)
                except (TypeError, ValueError):
                    return cls(known=False)
        elif charged_raw is not None:
            return cls(known=False)
        if offset < 0 or session_usd < 0 or unpriced < 0:
            return cls(known=False)
        return cls(offset=offset, charged=charged, session_usd=session_usd,
                   unpriced_calls=unpriced)


def _message_id(record: dict[str, Any], message: dict[str, Any], line_no: int) -> str:
    """The key a message is deduplicated on.

    `message.id` is what the streamed partials share. When it is absent the record's own uuid is
    the next best thing, and a line with neither is keyed by its position, which deduplicates
    nothing but also never collides with a real id and so never suppresses a real charge.
    """
    for candidate in (message.get("id"), record.get("uuid"), record.get("requestId")):
        if isinstance(candidate, str) and candidate:
            return candidate
    return f"#line-{line_no}"


def accrue(path: str | Path, state: TranscriptState | None = None
           ) -> tuple[float, int, TranscriptState]:
    """Price the transcript lines written since the last read.

    Returns (new estimated USD, number of newly seen calls nothing could price, new state).
    The cost is only ever the INCREASE, so calling this on every tool call of a session totals
    the session exactly once.
    """
    st = TranscriptState(offset=(state.offset if state else 0),
                         charged=dict(state.charged) if state else {},
                         session_usd=(state.session_usd if state else 0.0),
                         unpriced_calls=(state.unpriced_calls if state else 0))
    target = Path(path)
    try:
        size = target.stat().st_size
    except OSError:
        st.known = False
        return 0.0, 0, st

    if size < st.offset:
        # The file shrank. Either it was rotated or it was truncated, and in both cases the
        # spend recorded before this point is no longer readable from it. Restarting at zero
        # while claiming the total is authoritative would hand a blown day cap back its
        # headroom, so the offset resets AND the figure is declared incomplete.
        st = TranscriptState(known=False)

    try:
        with target.open("rb") as fh:
            fh.seek(st.offset)
            chunk = fh.read()
    except OSError:
        st.known = False
        return 0.0, 0, st

    # The tail of a transcript is routinely a half-written line, because the host writes it
    # asynchronously. Consuming it would both mis-parse it and skip the rest of that line
    # forever, so the offset stops at the last newline.
    end = chunk.rfind(b"\n")
    if end == -1:
        return 0.0, 0, st
    consumed = chunk[:end + 1]

    new_cost = 0.0
    new_unpriced = 0
    for line_no, raw in enumerate(consumed.split(b"\n")):
        if not raw.strip():
            continue
        try:
            record = json.loads(raw.decode("utf-8"))
        except (ValueError, UnicodeDecodeError):
            # A line we cannot read is a model call we cannot price. Skipping it quietly would
            # under-report spend on authority; the total becomes a floor instead.
            st.known = False
            continue
        if not isinstance(record, dict) or record.get("type") != "assistant":
            continue
        message = record.get("message")
        if not isinstance(message, dict):
            continue
        usage = message.get("usage")
        if not isinstance(usage, dict) or not usage:
            continue
        priced = cost_for(str(message.get("model") or ""), usage)
        cost = float(priced.get("cost_usd", 0.0) or 0.0)
        key = _message_id(record, message, line_no)
        already = st.charged.get(key)
        if already is None:
            delta = cost
            if not reliable(priced):
                new_unpriced += 1
        else:
            # The last usage for an id wins, and it only ever grows as the message streams. A
            # smaller figure would mean charging a refund into a spend ledger, which is how a
            # cap that has already been blown reads as untouched again.
            delta = max(0.0, cost - already)
        st.charged[key] = max(already or 0.0, cost)
        new_cost += delta

    if len(st.charged) > RECENT_IDS:
        st.charged = dict(list(st.charged.items())[-RECENT_IDS:])
    st.offset += len(consumed)
    st.session_usd = round(st.session_usd + new_cost, 6)
    st.unpriced_calls += new_unpriced
    return round(new_cost, 6), new_unpriced, st


# ---------------------------------------------------------------- the budget verdict


def deny_reason(scope: str, spent_usd: float, limit_usd: float, config_filename: str) -> str:
    """What the agent is told when a cap is already over.

    It has to do three things at once: refuse, tell the agent to stop rather than to find
    another route to the same spend, and name the one file where a human can raise the cap. A
    deny reason that only says "denied" gets retried immediately by the agent that read it.
    """
    return (f"estimated {scope} spend is ${spent_usd:,.4f}, over the ${limit_usd:,.4f} cap, so "
            f"this tool call is refused. Stop here and tell the person what happened rather "
            f"than working around it. Raise or remove the cap in {config_filename} to continue. "
            f"Spend is {ESTIMATE_CAVEAT}.")


def warn_reason(budget_id: str, scope: str, spent_usd: float, limit_usd: float) -> str:
    """The line attached to an allowed call that has crossed `warn_at`.

    A cost alert that arrives only once the cap has already blocked the work is a post-mortem,
    not a control.
    """
    pct = (spent_usd / limit_usd * 100.0) if limit_usd else 100.0
    return (f"{budget_id}: estimated {scope} spend ${spent_usd:,.4f} is {pct:.0f}% of the "
            f"${limit_usd:,.4f} cap ({ESTIMATE_CAVEAT})")


def unpriced_reason(count: int, deny: bool) -> str:
    plural = "" if count == 1 else "s"
    if deny:
        return (f"{count} model call{plural} in this session have no verified price, so they "
                f"cannot be counted against a spend cap and this call is refused")
    return (f"{UNPRICED_RULE}: {count} model call{plural} in this session have no verified "
            f"price, so they add $0.00 to every cap. The figures below are a floor, not a total.")


def verdict_for(budgets: list[tuple[str, str, float, float]], spent_by_scope: dict[str, float],
                unpriced_calls: int, on_unpriced: str, config_filename: str
                ) -> tuple[str, str, str] | None:
    """The verdict for spend ALREADY incurred, with no new model call to price.

    `budgets` is (id, scope, limit_usd, warn_at) per budget and `spent_by_scope` maps each scope
    to what has been spent against it, so this function holds no list of scopes of its own.
    Returns ("deny", rule id, reason), ("allow", "", warning), or None when nothing to say.

    Both engines call this. The installed one wraps the answer in a `policy.Decision`, the
    standalone renders it straight into the hook's JSON, and neither writes the sentence itself.
    """
    if not budgets:
        return None
    warning: str | None = None
    if unpriced_calls:
        if (on_unpriced or "warn").lower() == "deny":
            return "deny", UNPRICED_RULE, unpriced_reason(unpriced_calls, deny=True)
        warning = unpriced_reason(unpriced_calls, deny=False)
    for budget_id, scope, limit_usd, warn_at in budgets:
        spent = float(spent_by_scope.get(scope, 0.0) or 0.0)
        if spent > limit_usd + 1e-9:
            return "deny", budget_id, deny_reason(scope, spent, limit_usd, config_filename)
        if warning is None and warn_at > 0 and spent >= limit_usd * warn_at - 1e-9:
            warning = warn_reason(budget_id, scope, spent, limit_usd)
    if warning is None:
        return None
    return "allow", "", warning


#: Prefix on the state-file key that holds a transcript's read cursor. A host session id can
#: never start with it, so the two kinds of entry share one file without colliding.
STATE_PREFIX = "transcript:"


def state_key(path: str | Path) -> str:
    """The key the read offset and the charged-message map are held under.

    They belong to the TRANSCRIPT, because the transcript is the thing being read. Held per
    session instead, two session ids pointed at one transcript file each charged its entire
    history to the shared day ledger: a forked or re-identified session billed its parent's
    whole spend a second time, and the cap then refused work the user had already paid for.
    A cap that fails by stopping work is the worse direction to fail in.

    The identity is the resolved path plus the file's device and inode, so a rotated transcript
    that reuses the same path gets a fresh cursor rather than seeking into the middle of a
    different file. A transcript that shrinks in place is still caught by `accrue`.
    """
    target = Path(path)
    try:
        identity = str(target.resolve())
    except OSError:
        identity = str(target)
    try:
        stat = target.stat()
        if stat.st_ino:
            identity = f"{identity}|{stat.st_dev}|{stat.st_ino}"
    except OSError:
        # No stat means no rotation evidence, so the path alone identifies it. Refusing to
        # produce a key here would drop the cursor and recharge the transcript instead.
        pass
    digest = hashlib.sha256(identity.encode("utf-8", "replace")).hexdigest()
    return STATE_PREFIX + digest[:32]


def _entry_spend(data: Any, key: str) -> Any:
    entry = data.get(key) if isinstance(data, dict) else None
    if not isinstance(entry, dict) or "spend" not in entry:
        return None
    return entry.get("spend")


def find_state(data: Any, transcript_key: str, session_id: str) -> TranscriptState:
    """Assemble the spend cursor out of the two things it is actually keyed on.

    The offset, the charged-message map and the unpriced count come from the transcript entry,
    because they describe bytes already read. `session_usd` comes from the session entry,
    because a `session`-scope budget caps a session and not a file.
    """
    cursor_raw = _entry_spend(data, transcript_key)
    if cursor_raw is None:
        # Before this was keyed on the transcript the cursor lived under the session id, so a
        # session upgrading mid-flight would otherwise find no cursor and charge everything it
        # had already paid for. Adopt its own old one; it describes this same transcript.
        cursor_raw = _entry_spend(data, session_id)
    cursor = TranscriptState() if cursor_raw is None else TranscriptState.from_dict(cursor_raw)
    session_raw = _entry_spend(data, session_id)
    session = TranscriptState() if session_raw is None else TranscriptState.from_dict(session_raw)
    cursor.session_usd = session.session_usd
    cursor.known = cursor.known and session.known
    return cursor
