"""Generate the rule data AND the shared engine modules the zero-install guard hook reads.

The plugin has to work before Provenrail is installed, which means the hook cannot import
`provenrail.rulesets`. It reads a JSON copy instead. That copy is generated from the
catalogue by this script and checked in, so there is exactly one place a rule is written
and the copy cannot drift silently: `tests/test_guard_standalone.py` regenerates it and
fails if the checked-in file differs.

    python tools/vendor_guard_rules.py          # rewrite the vendored file
    python tools/vendor_guard_rules.py --check  # exit 1 if it is stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "plugins" / "provenrail-guard" / "scripts"
TARGET = SCRIPTS / "rules.json"

#: Modules the standalone hook needs verbatim. Both are stdlib-only by design, so they are
#: vendored as source rather than reimplemented: the segmentation that stops a heredoc body
#: being read as commands, and the predicates that tell `rm -rf .next` from `rm -rf ~`. A
#: hand-written second copy of either would drift, and the drift would be invisible until it
#: was a verdict the two engines disagreed about.
VENDORED_MODULES = ("shell.py", "predicates.py")

_BANNER = ("# Generated by tools/vendor_guard_rules.py from src/provenrail/%s. Do not edit:\n"
           "# edit the source module and regenerate, or the two engines will disagree.\n")


def build() -> dict:
    sys.path.insert(0, str(ROOT / "src"))
    from provenrail import rulesets
    from provenrail.guard import DEFAULT_PACKS

    packs = {}
    for pack, spec in rulesets.CATALOG.items():
        packs[pack] = {
            "title": spec["title"],
            "description": spec["description"],
            "rules": [{k: v for k, v in rule.items() if k in rulesets._ENGINE_FIELDS}
                      for rule in spec["rules"]],
        }
    return {
        "generated_by": "tools/vendor_guard_rules.py",
        "schema": 1,
        "default_packs": list(DEFAULT_PACKS),
        "packs": packs,
    }


def render() -> str:
    return json.dumps(build(), indent=2, sort_keys=False) + "\n"


def outputs() -> dict[Path, str]:
    """Every generated file, path to exact intended content."""
    out = {TARGET: render()}
    for name in VENDORED_MODULES:
        source = (ROOT / "src" / "provenrail" / name).read_text(encoding="utf-8")
        out[SCRIPTS / name] = (_BANNER % name) + source
    return out


def main(argv: list[str]) -> int:
    files = outputs()
    if "--check" in argv:
        stale = [p for p, text in files.items()
                 if (p.read_text(encoding="utf-8") if p.is_file() else "") != text]
        if stale:
            names = ", ".join(str(p.relative_to(ROOT)) for p in stale)
            print(f"stale: {names}; run: python tools/vendor_guard_rules.py", file=sys.stderr)
            return 1
        return 0
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
